# Generated by Django 5.0.4 on 2024-04-09 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('win_percentage', models.FloatField()),
                ('games_played', models.IntegerField()),
                ('code', models.CharField(max_length=10)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to=settings.AUTH_USER_MODEL)),
                ('member1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_member1', to=settings.AUTH_USER_MODEL)),
                ('member2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_member2', to=settings.AUTH_USER_MODEL)),
                ('member3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_member3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
    ]
