# Generated by Django 5.0.4 on 2024-04-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='team',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ties',
        ),
        migrations.RemoveField(
            model_name='team',
            name='win_percentage',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wins',
        ),
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
