# Generated by Django 5.0.4 on 2024-04-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player1_choice',
            new_name='team1_choice',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player2_choice',
            new_name='team2_choice',
        ),
    ]
