# Generated by Django 5.0.4 on 2024-04-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0002_rename_player1_choice_game_team1_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(max_length=50),
        ),
    ]
